export enum ActionType {
    SET_DATA = 'SET_DATA',
    SET_TESTS = 'SET_TESTS',
    SET_TOTAL_PAGE = 'SET_TOTAL_PAGE',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
    SET_TOTAL_SIZE = 'SET_TOTAL_SIZE',
    SET_CURRENT_SIZE = 'SET_CURRENT_SIZE',
    SET_SELECTED_STUDENTS ='SET_SELECTED_STUDENTS',
  }
  